speech_config:
  sample_rate: 16000
  feature_type: waveform
  preemphasis: 0.97
  normalize_signal: False
  padding: 0.0

decoder_config:
  type: characters
  blank_index: 0
  beam_width: 0
  norm_score: True
  lm_config: null
  vocabulary: ../../../../vocabularies/english.characters

model_config:
  name: deepspeech2
  conv_type: conv2d
  conv_kernels: [ [ 11, 41 ], [ 11, 21 ] ]
  conv_strides: [[ 2, 2 ], [ 1, 2 ] ]
  conv_filters: [ 32, 32 ]
  conv_activation: relu
  conv_dropout: 0.2
  conv_padding: same
  conv_initializer: he_uniform
  rnn_nlayers: 5
  rnn_type: lstm
  rnn_units: 512
  rnn_bidirectional: False
  rnn_unroll: False
  rnn_rowconv: 5
  rnn_rowconv_activation: relu
  rnn_dropout: 0.3
  rnn_initializer: glorot_uniform
  fc_nlayers: 1
  fc_units: 1024
  fc_activation: relu
  fc_dropout: 0.3
  fc_initializer: he_uniform
  blank: 0
  vocab_size: 29
  kernel_regularizer:
    class_name: l2
    value: 0.0005
  bias_regularizer:
    class_name: l2
    value: 0.0005
  initializer: glorot_uniform

learning_config:
  train_dataset_config:
    enabled: True
    sample_rate: 16000
    data_paths:
      - /home/hemanth/InHouseODV/odvModelTraining.hemanth.saigarladinne/data/LibriSpeech/t.tsv
    shuffle: False
    cache: False
    buffer_size: 1000
    drop_remainder: True
    stage: train
    metadata: null
    indefinite: True

  eval_dataset_config:
    enabled: True
    sample_rate: 16000
    data_paths:
      - /home/hemanth/InHouseODV/odvModelTraining.hemanth.saigarladinne/data/LibriSpeech/v.tsv
    shuffle: True
    cache: False
    buffer_size: 1000
    drop_remainder: True
    stage: eval
    metadata: null
    indefinite: True

  test_dataset_configs:
    enabled: True
    sample_rate: 16000
    data_paths:
      - /home/hemanth/InHouseODV/odvModelTraining.hemanth.saigarladinne/data/LibriSpeech/test.tsv
    shuffle: False
    cache: False
    buffer_size: null
    drop_remainder: False
    stage: test
    indefinite: False

  optimizer_config:
    class_name: SGD
    learning_rate:
      lr_scheduler: transformer
      initial_learning_rate: 0.001
      decay_steps: 10000 # around 5 epochs with batch size 16 and 8 tpus
      max_learning_rate: 0.0001
      power: 0.5
      cycle: False
    momentum: 0.9
    nesterov: True
  
  ga_steps: 0
  gradn_config: null
  pretrained: False

  running_config:
    batch_size: 8
    num_epochs: 200
    dataset_type: slice
    devices: [0]
    checkpoint:
      filepath: ../../../libri860/checkpoints/{epoch:02d}.h5
      save_best_only: False
      save_weights_only: True
      save_freq: epoch
    states_dir: libri860/states
    csv_logger: libri860/training.log
    tensorboard:
      log_dir: libri860/tensorboard
      histogram_freq: 1
      write_graph: True
      write_images: True
      update_freq: epoch
      profile_batch: 2
