speech_config:
  sample_rate: 16000
  feature_type: waveform
  preemphasis: 0.97
  normalize_signal: True # Whisper normalizes the signal
  padding: 0.0

model_config:
  name: moonshine
  d_model: 288
  encoder_num_blocks: 6
  decoder_num_blocks: 6
  fc_factor: 2
  encoder_activation: gelu
  decoder_activation: swiglu
  num_heads: 8 
  head_size: 32
  dropout: 0.1

learning_config:
  train_dataset_config:
    enabled: True
    data_paths:
      - /home/hemanth/InHouseODV/odvModelTraining.hemanth.saigarladinne/data/LibriSpeech/t.tsv
    shuffle: False
    cache: False
    buffer_size: 1000
    drop_remainder: True
    stage: train
    metadata: null
    indefinite: True

  eval_dataset_config:
    enabled: True
    data_paths:
      - /home/hemanth/InHouseODV/odvModelTraining.hemanth.saigarladinne/data/LibriSpeech/v.tsv
    shuffle: True
    cache: False
    buffer_size: 1000
    drop_remainder: True
    stage: eval
    metadata: null
    indefinite: True

  test_dataset_configs:
    enabled: True
    data_paths:
      - /home/hemanth/InHouseODV/odvModelTraining.hemanth.saigarladinne/data/LibriSpeech/test.tsv
    shuffle: False
    cache: False
    buffer_size: null
    drop_remainder: False
    stage: test
    indefinite: False

  optimizer_config:
    class_name: SGD
    learning_rate:
      lr_scheduler: transformer
      initial_learning_rate: 0.001
      decay_steps: 10000
      max_learning_rate: 0.0001
      power: 0.5
      cycle: False
    momentum: 0.9
    nesterov: True
  
  pretrained: False

  running_config:
    batch_size: 4
    num_epochs: 200
    dataset_type: slice
    devices: [0]
    checkpoint:
      filepath: ../../../libri860/checkpoints/{epoch:02d}.h5
      save_best_only: False
      save_weights_only: True
      save_freq: epoch
    states_dir: libri860/states
    csv_logger: libri860/training.log
    tensorboard:
      log_dir: libri860/tensorboard
      histogram_freq: 1
      write_graph: True
      write_images: True
      update_freq: epoch
      profile_batch: 2
